"""empty message

Revision ID: 668a866744ec
Revises: 949bd1a4b7c2
Create Date: 2026-08-12 15:22:10.530497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668a866744ec'
down_revision = '949bd1a4b7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_first_name'))
        batch_op.drop_index(batch_op.f('ix_post_last_name'))
        batch_op.drop_index(batch_op.f('ix_post_username'))
        batch_op.drop_column('first_name')
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_first_name'), ['first_name'], unique=False)

    # ### end Alembic commands ###
